In [17]:
from sklearn import decomposition
import pandas as pd
import numpy as np

In [15]:
test = pd.read_csv(r'd:\test.csv',encoding='utf8',header=None)
test

0        1        2       3       4      5       6      7     8   9   \
0    49.60  34917.0  24325.4  305.00  101350  98678  254.80  276.9  47.5   1   
1   275.80  14667.0  11114.4  775.00   75002  74677   30.00  109.0   9.1   1   
2     2.30   9372.5   8035.4    4.60    8111   8200    8.01  130.0   1.2   0   
3     7.10  13198.0  13266.4    1.10     708    695    6.10   80.0   0.4   0   
4     1.97   2466.7   2900.6   19.70    5358   5335   10.10   23.0   0.5   0   
5     2.40   2999.4   2218.2    0.80    2045   2100    8.90   10.0   1.5   1   
6     0.59   4120.8   5314.5    0.54   14680  13688   14.90  117.0   1.1   0   
7     0.72   2067.7   2364.0    3.00     367    298    7.20   60.0   2.5   0   
8     1.14   2751.9   3066.8    3.50    1429   1498    7.70    9.0   1.6   0   
9     1.29   4802.6   5026.1    2.70    7859   7789    6.50   45.0   1.9   0   
10    0.40    639.0    660.3    1.30      23     25    1.50    9.0   0.1   0   
11    0.26    430.7    608.1    2.00      33     28    2.50    7.0   0.4   0   
12    4.99   2141.2   2357.6    3.60     339    320    8.10    7.0   0.2   0   
13    0.36   1453.7   1362.2    3.50     796    785    3.70    9.0   0.1   0   
14    0.36   1657.5   2421.1    2.80     722    690    8.10    8.0   0.4   0   
15    1.14   5635.2   5649.6    3.00    2681   2530    5.40   20.0   0.3   0   
16    0.60   1055.9   1487.9    1.30      69     65    2.50    6.0   0.4   0   
17    0.08    795.3   1174.7    1.40      85     76    2.20    7.0   0.2   0   
18    0.90   2514.0   2644.4    2.60    1173   1104    5.50   43.0   0.8   0   
19    0.27    870.4    949.7    1.80     252    240    2.20   31.0   0.2   0   
20    0.41   1295.1   2052.3    2.60    2248   2135    6.00   12.0   0.8   0   
21    1.10   3544.2   4268.9    2.10     735    730    6.60   10.0   1.7   0   
22    0.22    899.3    888.2    1.80     220    218    3.60    7.0   0.5   0   
23    0.24   1712.8   1735.5    1.30      41     35    5.40    7.0   0.5   0   
24    0.20    558.4    631.9    1.70      65     64    2.50    7.0   0.2   0   
25    0.21    599.9   1029.0    1.10      69     70    3.70   85.7   0.1   0   
26    0.10    131.3    190.6    1.60      28     25    2.90    7.0   0.3   0   
27    0.44   3881.4   5067.3    0.90    2732   2500   11.20   10.0   1.5   0   
28    0.18   1024.8   1651.3    1.01     358    345    4.60   35.0   0.3   0   
29    0.46    682.9    784.2    1.80     103    109    2.20    8.0   0.4   0   
30    0.12    370.4    420.0    1.10      28     25    3.40   10.0   0.1   0   
31    0.03    552.4    555.1    0.80      54     49    3.50   10.0   0.4   0   
32    0.21   1256.5   2434.8    0.90    1265   1138    6.30   20.0   1.3   0   
33    0.09    320.6    745.7    1.10      37     25    2.70    8.0   0.3   0   
34    0.08    452.7    570.9    1.00      18     20    4.70    9.0   0.6   0   
35    0.13    967.9    947.2    1.00      74     65    4.00   25.0   1.4   0   
36    0.07    495.0    570.3    1.20      27     30    4.30    7.0   0.5   0   
37    0.17    681.9    537.4    1.10     113    120    2.90   12.0   0.4   0   
38    0.05    639.7    898.2    0.40       9     12    3.00    7.0   0.1   0   
39    0.65   2067.8   2084.2    2.50     414    398    7.30    6.0   0.7   0   
40    0.12    804.4   1416.4    3.30     579    602    4.20    7.0   1.8   0   

   ...     19      20  21       22      23   24       25    26  27  28  
0  ...  100.0     0.0   0   96.930   610.1  100  1718.22   6.7  28   5  
1  ...  100.0     0.0   0  100.000  1558.0  100  2063.17   5.5  64   5  
2  ...   67.3   342.3   0   99.960    18.3   53  1457.27   4.8   8   4  
3  ...   45.0    82.7   0   99.680     4.5   80  1718.22  13.8   0   3  
4  ...   74.5    98.2   0   99.640    79.8   54  1367.89   6.4  12   4  
5  ...   47.2   323.8   0   99.996    13.6   24  1249.67   2.7  12   3  
6  ...   11.8   872.6   0  100.000     9.3   52  1251.67  14.0  14   2  
7  ...   74.7   186.8   0   99.130    12.0   57  1800.45   2.7 

In [11]:
data = np.array(test,dtype=np.float64)
data

array([[  4.96000000e+01,   3.49170000e+04,   2.43254000e+04, ...,
          6.70000000e+00,   2.80000000e+01,   5.00000000e+00],
       [  2.75800000e+02,   1.46670000e+04,   1.11144000e+04, ...,
          5.50000000e+00,   6.40000000e+01,   5.00000000e+00],
       [  2.30000000e+00,   9.37250000e+03,   8.03540000e+03, ...,
          4.80000000e+00,   8.00000000e+00,   4.00000000e+00],
       ..., 
       [  5.00000000e-02,   6.39700000e+02,   8.98200000e+02, ...,
          7.00000000e+00,   0.00000000e+00,   4.00000000e+00],
       [  6.50000000e-01,   2.06780000e+03,   2.08420000e+03, ...,
          7.40000000e+00,   0.00000000e+00,   2.00000000e+00],
       [  1.20000000e-01,   8.04400000e+02,   1.41640000e+03, ...,
          7.00000000e+00,   0.00000000e+00,   2.00000000e+00]])

In [25]:
#主成分pca
pca = decomposition.PCA()
pca.fit(data)
pca.transform(data)
pca.explained_variance_ratio_

array([  9.83677746e-01,   1.56093758e-02,   3.79722691e-04,
         2.40186735e-04,   5.78276727e-05,   3.23313507e-05,
         1.51563661e-06,   5.73119923e-07,   3.72770106e-07,
         1.90753317e-07,   5.10360204e-08,   3.76345460e-08,
         2.64089549e-08,   1.90582272e-08,   1.05472763e-08,
         5.97053473e-09,   3.66159660e-09,   1.31868423e-09,
         8.27460034e-10,   3.55328142e-10,   2.66347382e-10,
         1.55095593e-10,   7.28745566e-11,   3.94843132e-11,
         6.11448014e-12,   4.54424290e-12,   2.15568364e-12,
         1.19642305e-13,   4.95310249e-33])

In [12]:
#因子分析factor
fa = decomposition.FactorAnalysis(n_components = 1)
fa.fit(data)
tran_data = fa.transform(data)

In [19]:
fa.get_precision()

array([[  1.10345448e-03,  -6.97925027e-10,  -5.95953914e-10,
         -2.08020044e-08,  -3.69457558e-07,  -1.42086756e-06,
         -7.40344876e-08,  -4.66570943e-08,  -5.15265297e-07,
         -7.81460020e-06,   4.89506262e-08,  -1.03411297e-05,
         -1.82209587e-06,  -1.21901199e-07,  -1.37271474e-06,
          4.24778379e-07,   2.95457920e-07,   5.68741617e-08,
          1.48590474e-08,  -1.89337992e-08,   3.48462391e-10,
         -0.00000000e+00,  -2.30581281e-09,  -1.03095096e-08,
         -5.47250367e-08,  -2.14280418e-09,   9.51041410e-09,
         -2.15761389e-07,  -7.85692199e-07],
       [ -6.97925027e-10,   1.38535278e-07,  -1.29045718e-11,
         -4.50439125e-10,  -8.00010117e-09,  -3.07669555e-08,
         -1.60311618e-09,  -1.01029595e-09,  -1.11573695e-08,
         -1.69214544e-07,   1.05995927e-09,  -2.23923106e-07,
         -3.94550091e-08,  -2.63960474e-09,  -2.97242717e-08,
          9.19799834e-09,   6.39773961e-09,   1.23153265e-09,
          3.21752472e-10,